name: Lint

on:
  pull_request:
  push:
    branches:
      - treescape

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Ruff
      uses: astral-sh/ruff-action@v3
